name: build-windows-docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      -
        name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        run: |
          docker build --file=DockerfileWindows -t friwidev/jcefbuild:windows-latest .
          docker push friwidev/jcefbuild:windows-latest  

